title: Bruce Lee # your name (or website title) here
logo: "https://www.pngkey.com/png/detail/73-730477_first-name-profile-image-placeholder-png.png" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  Put some info about yourself here
  <br><br>
  Put more info about yourself here if you want
  <br><br>
  <a href="https://www.linkedin.com/in/example/">View My LinkedIn Profile</a> 
  
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
